### PR TITLE
add default shell and startup commands

### PR DESCRIPTION
**Pull request by leb-kuchen**
This pull request resolves the issue #25.

### CODE REVIEW

**Comment by jackpot51** [comment]
Please resolve the conflicts.

**Comment by leb-kuchen** [comment]
Which error handling would you suggest for invalid commands?

**Comment by jackpot51** [comment]
We don't have much error handling beyond logs at this point. Ideally it would be shown to the user graphically.

**Comment by leb-kuchen** [comment]
Have you imagined something like this?

**Comment by nyabinary** [comment]
more merge conflicts :3

**Comment by jackpot51** [comment]
Profiles as currently implemented in cosmic-term provide similar functionality.

**Pull request closed without merging**
