### PR TITLE
fix ctrl or alt + arrows

### LINKED ISSUE #149: Alt or Ctrl + left/right arrows behaves incorrectly
Alt or Ctrl + left/right arrows should move the cursor forward or backward 1 word. Currently, it moves the cursor forward or backward by one character and inserts unwanted characters. Ctrl + arrows inserts `;5` and alt + arrows inserts `;3`

To recreate: 
- In a terminal, type a few words separated by spaces
- Hold alt or ctrl, then tap the left arrow

Version: `0.1.0~1709152706~22.04~36477e0`

### LINKED ISSUE #253: Implement Alt+Left/Right from Gnome terminal
These should mirror Alt+B and Alt+F which jump backwards and forward one word.

### LINKED ISSUE #260: Can't use zellij `Alt + <⬅⬆⬇➡>` shorcuts
When using [zellij](https://zellij.dev/) I can't navigate the terminal panes with `Alt + <⬅⬆⬇➡>`; instead `":3"` are inputted in the prompt.

image

This does not render zellij unusable in "cosmic-term" since zellij also allows `Alt + <hjkl>`, which does work.

### PR DESCRIPTION
**Pull request by leb-kuchen**
should fix #149, should fix #253, and should fix #260

Since the refactor in #122, csi sequences have been used for arrow sequences if `is_app_cursor` was set , before ss3 had been used for ctrl and alt modifiers. 
The custom logic for shift keys was applied to all modifiers in this commit. 
Even though I do not know, if this logic is still need, I still preserved it for shift keys. 
The  correct modifier for shift is 2 and was not applied before the patch, thus it could had been a workaround.

### CODE REVIEW

**Comment by leb-kuchen** [comment]
https://sw.kovidgoyal.net/kitty/keyboard-protocol/#legacy-functional-keys
The 2. form becomes the 3. form if no modifiers are set, so the `is_app_cusor` logic is correct,  but csi should not have been used.

**Comment by leb-kuchen** [comment]
@tobyrg Which shell are you using? I can select text in fish.
With ` kitty +kitten show_key -m kitty` you can see it correctly sends the text

**Comment by tobyrg** [comment]
@leb-kuchen I'm using the default bash shell on Pop!_OS.

**Comment by leb-kuchen** [comment]
Are you on the lattest commit?

**Comment by tobyrg** [comment]
Yes I'm on the latest commit, Ctrl Arrows key works great for moving arrow words but not selecting text. This is what I get from `kitty +kitten show_key -m kitty` 

```
Shift+LEFT PRESS
CSI 1 ; 2 D

Shift+RIGHT PRESS
CSI 1 ; 2 C
```

**Comment by leb-kuchen** [comment]
Which shell?

**Comment by tobyrg** [comment]
Bash, but I don't think is actually a thing in Bash from what I've found online.

**Comment by drakon64** [comment]
Patch c72010062db45f2d5a4655fa47ebd9f2617c30a4 is working fine against be808b56cf24d03fc99cf44b0885078a81a16523

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
